#ifndef	DIDPDS_VERSION_INCLUDED
#define DIDPDS_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#if SKYRIM
#define DIDPDS_DLL_NAME "DarkId.Papyrus.DebugServer.Skyrim.dll"
#elif FALLOUT
#define DIDPDS_DLL_NAME "DarkId.Papyrus.DebugServer.Fallout4.dll"
#endif

#define DIDPDS_VERSION_MAJOR	1

#ifndef DIDPDS_VERSION_MINOR
#define DIDPDS_VERSION_MINOR	7
#endif

#define DIDPDS_VERSION_PATCH	0
#define DIDPDS_VERSION_BETA	0
#define DIDPDS_VERSION_VERSTRING	MAKE_STR(DIDPDS_VERSION_MAJOR) "." MAKE_STR(DIDPDS_VERSION_MINOR) "." MAKE_STR(DIDPDS_VERSION_PATCH) "." MAKE_STR(DIDPDS_VERSION_BETA)

#endif
